[workspace]

[package]
name = "lru_fuzz_10065829839385020462"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lru_fuzz_10065829839385020462"
path = "src/lru_fuzz_10065829839385020462.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
lru = { path = "../../../../lru-0.6.6/" }
global_data = { path = "../../../../../../../../code/global_data" }