[workspace]

[package]
name = "stack_dst_fuzz_5075964383736025427"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stack_dst_fuzz_5075964383736025427"
path = "src/stack_dst_fuzz_5075964383736025427.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
stack_dst = { path = "../../../../stack_dst-0.6.0/" }
global_data = { path = "../../../../../../../../code/global_data" }