[workspace]

[package]
name = "http_fuzz_4521340454861179515"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "http_fuzz_4521340454861179515"
path = "src/http_fuzz_4521340454861179515.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
http = { path = "../../../../http-0.1.19/" }
global_data = { path = "../../../../../../../../code/global_data" }