[package]
edition = "2018"
name = "qwutils"
version = "0.3.0"
authors = [ "qwertz19281 <dellen903@gmail.com>",]
description = "some utilities"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/qwertz19281/rust_utils"

[dependencies]
bolero = "0.8.0"
arbitrary = "1.3.2"

[dependencies.boolinator]
version = "2.4"

[dev-dependencies.lazy_static]
version = "1.4"

[profile.fuzz]
inherits = "dev"
opt-level = 1
incremental = false
codegen-units = 1
