[package]
edition = "2018"
name = "ordnung"
version = "0.0.1"
authors = [ "Maciej Hirsz <hello@maciej.codes>",]
description = "Fast, vector-based map implementation that preserves insertion order."
documentation = "https://docs.rs/ordnung"
readme = "./README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/maciejhirsz/ordnung"

[dependencies]
bolero = "0.8.0"
arbitrary = "1.3.2"

[dependencies.ahash]
version = "0.3.2"

[profile.bench]
lto = "fat"
codegen-units = 1
debug-assertions = false

[profile.fuzz]
inherits = "dev"
opt-level = 1
incremental = false
codegen-units = 1

[dev-dependencies.fnv]
version = "1.0.6"

[dev-dependencies.rustc-hash]
version = "1.0"
