[workspace]

[package]
name = "toodee_fuzz_1303250201076264444"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "toodee_fuzz_1303250201076264444"
path = "src/toodee_fuzz_1303250201076264444.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
global_data = { path = "../../../../../../../../code/global_data" }
toodee = { path = "../../../../toodee-0.2.4/" }