[workspace]

[package]
name = "algorithmica_fuzz_17332966688754024222"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "algorithmica_fuzz_17332966688754024222"
path = "src/algorithmica_fuzz_17332966688754024222.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
algorithmica = { path = "../../../../algorithmica-0.1.8/" }
global_data = { path = "../../../../../../../../code/global_data" }