[package]
name = "test_secp256k112"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "=0.11.1"
secp256k1 = { path = "/home/cdc/Fuzzing-Target-Generator/erasan_dataset/secp256k1-0.22.0" }
