[workspace]

[package]
name = "toodee_fuzz_16392563738466338233"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "toodee_fuzz_16392563738466338233"
path = "src/toodee_fuzz_16392563738466338233.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
global_data = { path = "../../../../../../../../code/global_data" }
toodee = { path = "../../../../toodee-0.2.4/" }