[workspace]

[package]
name = "smallvec_fuzz_9754281663105997418"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "smallvec_fuzz_9754281663105997418"
path = "src/smallvec_fuzz_9754281663105997418.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
smallvec = { path = "../../../../smallvec-0.6.6/" }
global_data = { path = "../../../../../../../../code/global_data" }