[workspace]

[package]
name = "futures-task_fuzz_1245725561958974242"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "futures-task_fuzz_1245725561958974242"
path = "src/futures-task_fuzz_1245725561958974242.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
futures-task = { path = "../../../../../futures-0.3.3/futures-task/" }
global_data = { path = "../../../../../../../../../code/global_data" }