[package]
name = "simple-slab"
version = "0.3.2"
authors = [ "Nathan Sizemore <nathanrsizemore@gmail.com>",]
description = "Fast and lightweight Slab Allocator."
repository = "https://github.com/nathansizemore/simple-slab"
readme = "README.md"
keywords = [ "slab", "allocator",]
license = "MPL-2.0"

[dependencies]
libc = "^0.2"
bolero = "0.8.0"
arbitrary = "1.3.2"

[profile.fuzz]
inherits = "dev"
opt-level = 1
incremental = false
codegen-units = 1
