[package]
name = "test_rusqlite34"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "*"
rusqlite = {path="/RPG/erasan_dataset/rusqlite-0.26.1", features = ["bundled"]}
