[package]
name = "test_rdiff2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "*"
rdiff = {path="/RPG/erasan_dataset/rdiff-0.1.2"}
