[workspace]

[package]
name = "llm_only_target_5"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "llm_only_target_5"
path = "src/llm_only_target_5.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
simple-slab = { path = "../../../../../../../../dataset/erasan_crates/simple-slab-0.3.2/" }
global_data = { path = "../../../../../../../../code/global_data" }