[workspace]

[package]
name = "llm_only_target_8"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "llm_only_target_8"
path = "src/llm_only_target_8.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
toodee = { path = "../../../../toodee-0.2.4/" }
global_data = { path = "../../../../../../../../code/global_data" }