[workspace]

[package]
name = "simple-slab_fuzz_7444962498856210082"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "simple-slab_fuzz_7444962498856210082"
path = "src/simple-slab_fuzz_7444962498856210082.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
global_data = { path = "../../../../../../../../code/global_data" }
simple-slab = { path = "../../../../simple-slab-0.3.2/" }