[package]
name = "string-interner"
version = "0.7.0"
authors = ["Robbepop"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/robbepop/string-interner"
documentation = "https://docs.rs/string-interner"
keywords = ["interner", "intern", "string", "str", "symbol"]
description = """An efficient string interning data structure with minimal memory-footprint
and fast access to the underlying contents.
"""
categories = ["data-structures"]

[dependencies]
serde = { version = "1.0.0", optional = true }

[dev-dependencies]
fnv = "1.0.0" # required bench tests
serde_json = "1.0.0" # required for testing the serde imlementation
lazy_static = "1.0.0" # required for bench tests

[features]
default       = ["serde_support"]
bench         = []
serde_support = ["serde"]

[badges]
travis-ci = { repository = "Robbepop/string-interner" }
appveyor = { repository = "Robbepop/string-interner", branch = "master", service = "github" }
