[workspace]

[package]
name = "smallvec_fuzz_4440273133123764458"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "smallvec_fuzz_4440273133123764458"
path = "src/smallvec_fuzz_4440273133123764458.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
smallvec = { path = "../../../../smallvec-0.6.6/" }
global_data = { path = "../../../../../../../../code/global_data" }