[workspace]
members = [
	"test_bumpalo7",
	"replay_bumpalo7",
	"test_bumpalo17",
	"replay_bumpalo17",
	"test_bumpalo14",
	"replay_bumpalo14",
	"test_bumpalo3",
	"replay_bumpalo3",
	"test_bumpalo27",
	"replay_bumpalo27",
	"test_bumpalo28",
	"replay_bumpalo28",
	"test_bumpalo16",
	"replay_bumpalo16",
	"test_bumpalo10",
	"replay_bumpalo10",
	"test_bumpalo20",
	"replay_bumpalo20",
	"test_bumpalo13",
	"replay_bumpalo13",
	"test_bumpalo11",
	"replay_bumpalo11",
	"test_bumpalo8",
	"replay_bumpalo8",
	"test_bumpalo15",
	"replay_bumpalo15",
	"test_bumpalo24",
	"replay_bumpalo24",
	"test_bumpalo26",
	"replay_bumpalo26",
	"test_bumpalo22",
	"replay_bumpalo22",
	"test_bumpalo1",
	"replay_bumpalo1",
	"test_bumpalo4",
	"replay_bumpalo4",
	"test_bumpalo19",
	"replay_bumpalo19",
	"test_bumpalo25",
	"replay_bumpalo25",
	"test_bumpalo9",
	"replay_bumpalo9",
	"test_bumpalo29",
	"replay_bumpalo29",
	"test_bumpalo23",
	"replay_bumpalo23",
	"test_bumpalo2",
	"replay_bumpalo2",
	"test_bumpalo6",
	"replay_bumpalo6",
	"test_bumpalo12",
	"replay_bumpalo12",
	"test_bumpalo30",
	"replay_bumpalo30",
	"test_bumpalo18",
	"replay_bumpalo18",
	"test_bumpalo21",
	"replay_bumpalo21",
]
