[workspace]

[package]
name = "toodee_fuzz_3639831062231178506"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "toodee_fuzz_3639831062231178506"
path = "src/toodee_fuzz_3639831062231178506.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
toodee = { path = "../../../../toodee-0.2.4/" }
global_data = { path = "../../../../../../../../code/global_data" }