[workspace]

[package]
name = "slice-deque_fuzz_5656338007438782333"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "slice-deque_fuzz_5656338007438782333"
path = "src/slice-deque_fuzz_5656338007438782333.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
slice-deque = { path = "../../../../slice-deque-0.3.0/" }
global_data = { path = "../../../../../../../../code/global_data" }