[workspace]

[package]
name = "endian_trait_fuzz_15160447695257319408"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "endian_trait_fuzz_15160447695257319408"
path = "src/endian_trait_fuzz_15160447695257319408.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
endian_trait = { path = "../../../../endian_trait-0.6.0/" }
global_data = { path = "../../../../../../../../code/global_data" }