[workspace]

[package]
name = "smallvec_fuzz_4805272068686460794"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "smallvec_fuzz_4805272068686460794"
path = "src/smallvec_fuzz_4805272068686460794.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
smallvec = { path = "../../../../../../../../dataset/erasan_crates/smallvec-1.6.0/" }
global_data = { path = "../../../../../../../../code/global_data" }