[workspace]

[package]
name = "toodee_fuzz_9006285366408838861"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "toodee_fuzz_9006285366408838861"
path = "src/toodee_fuzz_9006285366408838861.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
global_data = { path = "../../../../../../../../code/global_data" }
toodee = { path = "../../../../toodee-0.2.4/" }