[workspace]

[package]
name = "slice-deque_fuzz_11641291300097988306"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "slice-deque_fuzz_11641291300097988306"
path = "src/slice-deque_fuzz_11641291300097988306.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
slice-deque = { path = "../../../../slice-deque-0.3.0/" }
global_data = { path = "../../../../../../../../code/global_data" }