[package]
name = "test_algorithmica0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "*"
algorithmica = {path="/RPG/erasan_dataset/algorithmica-0.1.8"}
