[workspace]

[package]
name = "qwutils_fuzz_2249377158105559971"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "qwutils_fuzz_2249377158105559971"
path = "src/qwutils_fuzz_2249377158105559971.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
qwutils = { path = "../../../../qwutils-0.3.0/" }
global_data = { path = "../../../../../../../../code/global_data" }