[workspace]
members = [
	"test_pnet_packet21",
	"replay_pnet_packet21",
	"test_pnet_packet19",
	"replay_pnet_packet19",
	"test_pnet_packet1",
	"replay_pnet_packet1",
	"test_pnet_packet8",
	"replay_pnet_packet8",
	"test_pnet_packet14",
	"replay_pnet_packet14",
	"test_pnet_packet4",
	"replay_pnet_packet4",
	"test_pnet_packet12",
	"replay_pnet_packet12",
	"test_pnet_packet18",
	"replay_pnet_packet18",
	"test_pnet_packet5",
	"replay_pnet_packet5",
	"test_pnet_packet10",
	"replay_pnet_packet10",
	"test_pnet_packet16",
	"replay_pnet_packet16",
	"test_pnet_packet6",
	"replay_pnet_packet6",
	"test_pnet_packet15",
	"replay_pnet_packet15",
	"test_pnet_packet2",
	"replay_pnet_packet2",
	"test_pnet_packet3",
	"replay_pnet_packet3",
	"test_pnet_packet17",
	"replay_pnet_packet17",
	"test_pnet_packet11",
	"replay_pnet_packet11",
	"test_pnet_packet0",
	"replay_pnet_packet0",
	"test_pnet_packet7",
	"replay_pnet_packet7",
	"test_pnet_packet13",
	"replay_pnet_packet13",
	"test_pnet_packet20",
	"replay_pnet_packet20",
	"test_pnet_packet9",
	"replay_pnet_packet9",
]
