[workspace]

[package]
name = "smallvec_fuzz_4336120526536135867"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "smallvec_fuzz_4336120526536135867"
path = "src/smallvec_fuzz_4336120526536135867.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
global_data = { path = "../../../../../../../../code/global_data" }
smallvec = { path = "../../../../../../../../dataset/erasan_crates/smallvec-1.6.0/" }