[workspace]
members = [
	"test_rusqlite3",
	"replay_rusqlite3",
	"test_rusqlite7",
	"replay_rusqlite7",
	"test_rusqlite0",
	"replay_rusqlite0",
	"test_rusqlite31",
	"replay_rusqlite31",
	"test_rusqlite21",
	"replay_rusqlite21",
	"test_rusqlite32",
	"replay_rusqlite32",
	"test_rusqlite1",
	"replay_rusqlite1",
	"test_rusqlite28",
	"replay_rusqlite28",
	"test_rusqlite33",
	"replay_rusqlite33",
	"test_rusqlite14",
	"replay_rusqlite14",
	"test_rusqlite25",
	"replay_rusqlite25",
	"test_rusqlite24",
	"replay_rusqlite24",
	"test_rusqlite13",
	"replay_rusqlite13",
	"test_rusqlite8",
	"replay_rusqlite8",
	"test_rusqlite6",
	"replay_rusqlite6",
	"test_rusqlite18",
	"replay_rusqlite18",
	"test_rusqlite20",
	"replay_rusqlite20",
	"test_rusqlite29",
	"replay_rusqlite29",
	"test_rusqlite36",
	"replay_rusqlite36",
	"test_rusqlite34",
	"replay_rusqlite34",
	"test_rusqlite11",
	"replay_rusqlite11",
	"test_rusqlite4",
	"replay_rusqlite4",
	"test_rusqlite16",
	"replay_rusqlite16",
	"test_rusqlite19",
	"replay_rusqlite19",
	"test_rusqlite23",
	"replay_rusqlite23",
	"test_rusqlite26",
	"replay_rusqlite26",
	"test_rusqlite5",
	"replay_rusqlite5",
	"test_rusqlite27",
	"replay_rusqlite27",
	"test_rusqlite22",
	"replay_rusqlite22",
	"test_rusqlite15",
	"replay_rusqlite15",
	"test_rusqlite10",
	"replay_rusqlite10",
	"test_rusqlite37",
	"replay_rusqlite37",
	"test_rusqlite2",
	"replay_rusqlite2",
	"test_rusqlite30",
	"replay_rusqlite30",
	"test_rusqlite35",
	"replay_rusqlite35",
	"test_rusqlite9",
	"replay_rusqlite9",
	"test_rusqlite38",
	"replay_rusqlite38",
	"test_rusqlite17",
	"replay_rusqlite17",
	"test_rusqlite12",
	"replay_rusqlite12",
]
