[workspace]

[package]
name = "through_fuzz_15538194288612094996"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "through_fuzz_15538194288612094996"
path = "src/through_fuzz_15538194288612094996.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
through = { path = "../../../../through/" }
global_data = { path = "../../../../../../../../code/global_data" }