[workspace]

[package]
name = "bumpalo_fuzz_1619006235460184034"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bumpalo_fuzz_1619006235460184034"
path = "src/bumpalo_fuzz_1619006235460184034.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
bumpalo = { path = "../../../../bumpalo-3.11.0/" }
global_data = { path = "../../../../../../../../code/global_data" }