[package]
name = "sparsey"
version = "0.7.0"
edition = "2021"
description = "Sparse set-based entity component system"
authors = ["Tudor-Cristian Lechintan <lechintantudor02@gmail.com>"]
repository = "https://github.com/LechintanTudor/sparsey"
keywords = ["ecs", "entity", "gamedev", "sparse"]
categories = ["data-structures", "game-development"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[features]
default = ["parallel"]
parallel = ["rayon"]

[dependencies]
atomic_refcell = "0.1.8"
downcast-rs = "1.2"
rustc-hash = "1.1"

rayon = { version = "1.5", optional = true }

[dev-dependencies]
rayon = "1.5"
