[package]
name = "test_secp256k132"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "*"
secp256k1 = {path="/RPG/erasan_dataset/secp256k1-0.22.0"}
