[package]
name = "test_pnet_packet5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "=0.11.1"
pnet_packet = { path = "/home/cdc/Fuzzing-Target-Generator/erasan_dataset/pnet_packet-0.26.0" }
