[package]
name = "test_rdiff1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "=0.11.1"
rdiff = { path = "/home/cdc/Fuzzing-Target-Generator/erasan_dataset/rdiff-0.1.2" }
