[workspace]

[package]
name = "smallvec_fuzz_4155452684639567898"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "smallvec_fuzz_4155452684639567898"
path = "src/smallvec_fuzz_4155452684639567898.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
global_data = { path = "../../../../../../../../code/global_data" }
smallvec = { path = "../../../../smallvec-1.6.0/" }