[workspace]

[package]
name = "pnet_packet_fuzz_10031078553328861880"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pnet_packet_fuzz_10031078553328861880"
path = "src/pnet_packet_fuzz_10031078553328861880.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
pnet_packet = { path = "../../../../pnet_packet-0.26.0/" }
global_data = { path = "../../../../../../../../code/global_data" }