[workspace]

[package]
name = "llm_only_target_11"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "llm_only_target_11"
path = "src/llm_only_target_11.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
smallvec = { path = "../../../../smallvec-1.6.0/" }
global_data = { path = "../../../../../../../../code/global_data" }