[package]
name = "test_string_interner1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "=0.11.1"
string-interner = { path = "/home/cdc/Fuzzing-Target-Generator/erasan_dataset/string-interner-0.7.0" }
