[workspace]

[package]
name = "smallvec_fuzz_13793808457219779298"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "smallvec_fuzz_13793808457219779298"
path = "src/smallvec_fuzz_13793808457219779298.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
smallvec = { path = "../../../../smallvec-1.6.0/" }
global_data = { path = "../../../../../../../../code/global_data" }