[workspace]

[package]
name = "rusqlite_fuzz_14091872570678981962"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rusqlite_fuzz_14091872570678981962"
path = "src/rusqlite_fuzz_14091872570678981962.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
global_data = { path = "../../../../../../../../code/global_data" }
rusqlite = { path = "../../../../rusqlite-0.26.1/", features = ["bundled"] }