[workspace]

[package]
name = "arc-swap_fuzz_17095977883110004252"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "arc-swap_fuzz_17095977883110004252"
path = "src/arc-swap_fuzz_17095977883110004252.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
arc-swap = { path = "../../../../arc-swap-1.0.0/" }
global_data = { path = "../../../../../../../../code/global_data" }