[package]
edition = "2018"
name = "smallvec"
version = "1.6.0"
authors = [ "The Servo Project Developers",]
description = "'Small vector' optimization: store up to a small number of items on the stack"
documentation = "https://docs.rs/smallvec/"
readme = "README.md"
keywords = [ "small", "vec", "vector", "stack", "no_std",]
categories = [ "data-structures",]
license = "MIT/Apache-2.0"
repository = "https://github.com/servo/rust-smallvec"

[dependencies]
bolero = "0.8.0"
arbitrary = "1.3.2"

[features]
const_generics = []
may_dangle = []
specialization = []
union = []
write = []

[dependencies.serde]
version = "1"
optional = true
default-features = false

[dev-dependencies.bincode]
version = "1.0.1"

[profile.fuzz]
inherits = "dev"
opt-level = 1
incremental = false
codegen-units = 1
