[workspace]

[package]
name = "toodee_fuzz_15289259621227662867"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "toodee_fuzz_15289259621227662867"
path = "src/toodee_fuzz_15289259621227662867.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
global_data = { path = "../../../../../../../../code/global_data" }
toodee = { path = "../../../../../../../../dataset/erasan_crates/toodee-0.2.4/" }