[workspace]

[package]
name = "stackvector_fuzz_12301739073432993420"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stackvector_fuzz_12301739073432993420"
path = "src/stackvector_fuzz_12301739073432993420.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
stackvector = { path = "../../../../stackvector-1.0.8/" }
global_data = { path = "../../../../../../../../code/global_data" }