[workspace]

[package]
name = "cbox_fuzz_17589016483673457936"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cbox_fuzz_17589016483673457936"
path = "src/cbox_fuzz_17589016483673457936.rs"

[dependencies]
afl = "=0.15.7"
home = "=0.5.9"
cbox = { path = "../../../../cbox-0.3.0/" }
global_data = { path = "../../../../../../../../code/global_data" }