[package]
name = "stack_dst"
version = "0.6.0"
authors = [ "John Hodge <tpg@mutabah.net>",]
description = "A wrapper that allows storage of unsized values of up to a fixed size inline (without boxing)"
documentation = "http://thepowersgang.github.io/stack_dst-rs/target/doc/stack_dst/"
readme = "README.md"
keywords = [ "stack", "dst",]
license = "MIT OR Apache-2.0"
repository = "https://github.com/thepowersgang/stack_dst-rs"

[features]
alloc = []
default = [ "std", "alloc",]
std = []
unsize = []

[dependencies]
bolero = "0.8.0"
arbitrary = "1.3.2"

[profile.fuzz]
inherits = "dev"
opt-level = 1
incremental = false
codegen-units = 1

[package.metadata.docs.rs]
all-features = true
